import os
import tempfile
import textwrap
from ament_index_python.packages import get_package_share_directory
from launch import LaunchDescription
from launch.actions import IncludeLaunchDescription, DeclareLaunchArgument, OpaqueFunction, SetEnvironmentVariable
from launch.launch_description_sources import PythonLaunchDescriptionSource
from launch.substitutions import LaunchConfiguration
from launch_ros.actions import Node


def _as_bool(value):
    return str(value).strip().lower() in ('1', 'true', 'yes', 'on')


def _write_bridge_config(world_name):
    bridge_config = textwrap.dedent(f"""\
        # Generated by 01_sim_world.launch.py.
        # Keep /clock world-scoped so ROS time follows the selected Gazebo world.
        ---
        - ros_topic_name: "/clock"
          gz_topic_name: "/world/{world_name}/clock"
          ros_type_name: "rosgraph_msgs/msg/Clock"
          gz_type_name: "gz.msgs.Clock"
          direction: GZ_TO_ROS

        - ros_topic_name: "/scan"
          gz_topic_name: "/scan"
          ros_type_name: "sensor_msgs/msg/LaserScan"
          gz_type_name: "gz.msgs.LaserScan"
          direction: GZ_TO_ROS

        - ros_topic_name: "/imu"
          gz_topic_name: "/imu"
          ros_type_name: "sensor_msgs/msg/Imu"
          gz_type_name: "gz.msgs.IMU"
          direction: GZ_TO_ROS

        - ros_topic_name: "/odom"
          gz_topic_name: "/odom"
          ros_type_name: "nav_msgs/msg/Odometry"
          gz_type_name: "gz.msgs.Odometry"
          direction: GZ_TO_ROS

        - ros_topic_name: "/cmd_vel"
          gz_topic_name: "/cmd_vel"
          ros_type_name: "geometry_msgs/msg/Twist"
          gz_type_name: "gz.msgs.Twist"
          direction: ROS_TO_GZ

        - ros_topic_name: "/camera/image"
          gz_topic_name: "/camera/image"
          ros_type_name: "sensor_msgs/msg/Image"
          gz_type_name: "gz.msgs.Image"
          direction: GZ_TO_ROS

        - ros_topic_name: "/camera/depth_image"
          gz_topic_name: "/camera/depth_image"
          ros_type_name: "sensor_msgs/msg/Image"
          gz_type_name: "gz.msgs.Image"
          direction: GZ_TO_ROS

        - ros_topic_name: "/camera/points"
          gz_topic_name: "/camera/points"
          ros_type_name: "sensor_msgs/msg/PointCloud2"
          gz_type_name: "gz.msgs.PointCloudPacked"
          direction: GZ_TO_ROS

        - ros_topic_name: "/camera/camera_info"
          gz_topic_name: "/camera/camera_info"
          ros_type_name: "sensor_msgs/msg/CameraInfo"
          gz_type_name: "gz.msgs.CameraInfo"
          direction: GZ_TO_ROS
        """)

    safe_world = ''.join(c if c.isalnum() or c in ('_', '-') else '_' for c in world_name)
    config_path = os.path.join(tempfile.gettempdir(), f'spooder_bridge_{safe_world}.yaml')
    with open(config_path, 'w', encoding='utf-8') as config_file:
        config_file.write(bridge_config)
    return config_path


def _launch_setup(context, *args, **kwargs):
    pkg_ros_gz_sim = get_package_share_directory('ros_gz_sim')
    pkg_spooder_gazebo = get_package_share_directory('spooder_gazebo')

    world_name = LaunchConfiguration('world').perform(context)
    use_sim_time = _as_bool(LaunchConfiguration('use_sim_time').perform(context))
    headless = _as_bool(LaunchConfiguration('headless').perform(context))

    world_file = os.path.join(pkg_spooder_gazebo, 'worlds', f'{world_name}.sdf')
    gz_args = f'-r -v 4 {"-s " if headless else ""}{world_file}'
    bridge_config = _write_bridge_config(world_name)

    # Force localhost discovery so ros_gz_sim create / bridge can find the
    # Gazebo server (especially under headless -s and multi-iface hosts).
    gz_env = {'GZ_IP': '127.0.0.1'}

    gazebo = IncludeLaunchDescription(
        PythonLaunchDescriptionSource(
            os.path.join(pkg_ros_gz_sim, 'launch', 'gz_sim.launch.py')
        ),
        launch_arguments={'gz_args': gz_args}.items(),
    )

    bridge = Node(
        package='ros_gz_bridge',
        executable='parameter_bridge',
        name='ros_gz_bridge',
        parameters=[{
            'config_file': bridge_config,
            'use_sim_time': use_sim_time
        }],
        additional_env=gz_env,
        output='screen'
    )

    return [gazebo, bridge]


def generate_launch_description():
    return LaunchDescription([
        SetEnvironmentVariable('GZ_IP', '127.0.0.1'),
        DeclareLaunchArgument('use_sim_time', default_value='true'),
        DeclareLaunchArgument('world', default_value='test_world'),
        DeclareLaunchArgument(
            'headless',
            default_value='false',
            description='Run Gazebo server-only when true; GUI remains the default'
        ),
        OpaqueFunction(function=_launch_setup),
    ])
